// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SamplesDB;

namespace SamplesDB.Migrations
{
    [DbContext(typeof(SamplesContext))]
    partial class SamplesContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7");

            modelBuilder.Entity("SamplesDB.Sample", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeatExchangersAmount")
                        .HasColumnType("INTEGER");

                    b.Property<double>("ReactionMassConsumption")
                        .HasColumnType("REAL");

                    b.Property<double>("ReactorPressure")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("Samples");
                });
#pragma warning restore 612, 618
        }
    }
}
